# Generated by Django 5.0.6 on 2024-05-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_options_alter_status_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
